version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "11270922"
    ports:
      - "15432:5432"
    volumes:
      -  /Users/andersons.andrade/Documents/docker/postgresSQL/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "asantos919@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "11270922"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge